### TRIPS GET ALL
GET http://localhost:8080/api/trips

### TRIP GET BY ID
GET http://localhost:8080/api/trips/1

### TRIP CREATE/POST
POST http://localhost:8080/api/trips
Content-Type: application/json

{
  "tripName": "Japan Adventure",
  "participants": [
    { "id": 1, "name": "Henry" },
    { "id": 2, "name": "Van" },
    { "id": 3, "name": "Khoa" }
  ]
}

### TRIP ID DELETE
DELETE http://localhost:8080/api/trips/2



### TRIP ID ALL EXPENSES
GET http://localhost:8080/api/trips/1/expenses

### TRIP ID SPECIFIC EXPENSE
GET http://localhost:8080/api/trips/1/expenses/3

### EXPENSE BY ID GET
GET http://localhost:8080/api/expenses/1







### EXPENSE ID DELETE
DELETE http://localhost:8080/api/expenses/3





### TRIP ID - EXPENSE CREATE/POST
POST http://localhost:8080/api/trips/1/expenses
Content-Type: application/json

{
  "title": "Lunch",
  "amount": 3000,
  "date": "2025-10-06",
  "exchangeRate": 148,
  "participants": [
    { "id": 1, "name": "Henry" },
    { "id": 2, "name": "Van" },
    { "id": 3, "name": "Khoa" }
  ],
  "payers": [
    { "person": { "id": 1, "name": "Henry" }, "amount": 2000 },
    { "person": { "id": 2, "name": "Van" }, "amount": 1000 }
  ],
  "splits": [
    { "person": { "id": 1, "name": "Henry" }, "amount": 1000 },
    { "person": { "id": 2, "name": "Van" }, "amount": 1000 },
    { "person": { "id": 3, "name": "Khoa" }, "amount": 1000 }
  ]
}




### PERSONS  - GET ALL
GET http://localhost:8080/api/persons